repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: redis
    url: oci://registry-1.docker.io/bitnamicharts

helmfiles:
- path: app1/helmfile.yaml
- path: app2/helmfile.yaml
