repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
- name: app1
  namespace: app1
  values:
  - values-app1.yaml
  chart: oci://registry-1.docker.io/bitnamicharts/redis
  version: 20.11.4

- name: app2
  namespace: app2
  values:
  - values-app2.yaml
  chart: oci://registry-1.docker.io/bitnamicharts/redis
  version: 20.11.4
